-- CreateTable
CREATE TABLE `Src` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL,
    `link` VARCHAR(500) NOT NULL,
    `description` TEXT NOT NULL,
    `status` ENUM('OPEN', 'IN_OPOGRESS', 'CLOSED') NOT NULL DEFAULT 'CLOSED',
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
